.github/workflows/Cargo.yml, bouffalo-rt/build.rs, examples/peripherals/lz4d-demo/src/main.rs
In this pr, GitHub Actions' behavior conforms to the definition of this script. There are three jobs `fmt`, `test-bouffalo-hal` and `build-bouffalo-hal`.
- `fmt`: format all packages on push and pull request.
- `test-bouffalo-hal`: test three main packages `bouffalo-hal`, `bouffalo-rt` and `blri` on push and pull request by using command `cargo test`.
- `build-bouffalo-hal`: build a series of examples, such as `gpio-demo`, `i2c-demo`, `jtag-demo`, `lz4d-demo`, `pwm-demo`, `sdcard-demo`, `sdcard-gpt-demo`, `spi-demo` and `uart-demo` by running the command `cargo build --target riscv64imac-unknown-none-elf --release -p xxx-demo`.
The GitHub Actions result are as follows:
Moreover, fix the type mismatch for `static LZ4_INPUT` with `&'static [u8]` instead of `&[u8; 1182]` in the example …
=> ci: create cargo format, build and test github actions

examples/peripherals/uart-cli-demo/Cargo.toml, examples/peripherals/uart-cli-demo/src/main.rs
Add embedded-cli crate support for `uart-cli-demo`. Now, in addition to the original commands in `uart-demo`, `uart-cli-demo` features the command-line menu with autocomplete, history, and help command.
Ref: [embedded_cli](https://docs.rs/embedded-cli/latest/embedded_cli/), [Readme](https://github.com/funbiscuit/embedded-cli-rs/blob/main/README.md) and [Example](https://github.com/funbiscuit/embedded-cli-rs/blob/main/examples/arduino/src/main.rs).
=> examples: add cli support for uart-demo

examples/peripherals/uart-cli-demo/README.md
Add flash guide for `uart-cli-demo` example on Windows in `examples\peripherals\uart-cli-demo\README.md`, with which we can have a test on M1s Dock.
=> docs: add the guide for `uart-cli-demo` example

Cargo.toml, examples/peripherals/psram-demo/Cargo.toml, examples/peripherals/psram-demo/README.md, examples/peripherals/psram-demo/build.rs, examples/peripherals/psram-demo/src/main.rs, examples/peripherals/psram-demo/src/psram.rs
To run more complex applications like the Linux kernel, we need more memory. Therefore, we plan to support PSRAM (Pseudo-Static Random Access Memory).
By analyzing the code in [bouffalo_sdk](https://github.com/bouffalolab/bouffalo_sdk), we have a basic understanding of the PSRAM initialization process and ported it to Rust, completing the psram-demo. This program initializes PSRAM by directly reading and writing memory, runs a simple test and outputs the result through the serial port. We flashed it into the sipeed M1s DOCK board, and it ran successfully. However, the program has some issues, including a 0.3%~1% error rate in memory read/write operations and unexpected read/write latency (likely due to clock configuration). We will continue to improve it.
=> psram: add example for initializing and testing PSRAM

examples/README.md, examples/peripherals/sdcard-demo/Cargo.toml, examples/peripherals/sdcard-demo/README.md, examples/peripherals/sdcard-demo/src/main.rs, examples/peripherals/sdcard-gpt-demo/Cargo.toml, examples/peripherals/sdcard-gpt-demo/README.md, examples/peripherals/sdcard-gpt-demo/src/main.rs, examples/peripherals/spi-demo/src/main.rs
fix broken spi related examples and update docs
- spi-demo
Change the spi device from spi0 to spi1, and it will run correctly. The running results are as follows:
- sdcard-demo and sdcard-gpt-demo
Changing the version of the dependency embedded-sdmmc to 0.6.0, the two demos can run normally. The reason why the 0.8.0 version cannot run normally is still being investigated. In addition, the requirements for pins have been added to README. The running results are as follows:
=> examples: fix broken spi related examples

.cargo/config.toml, examples/peripherals/sdcard-demo/README.md, examples/peripherals/sdcard-gpt-demo/README.md, examples/peripherals/spi-demo/README.md
- add flash tutorials to `spi-demo`, `sdcard-demo`, `sdcard-gpt-demo`
- add `blri` command, use `blri` by `cargo blri <file_path>`
=> docs(examples): add flash tutorials to spi related examples

bouffalo-hal/src/spi.rs, examples/peripherals/sdcard-demo/Cargo.toml, examples/peripherals/sdcard-demo/src/main.rs, examples/peripherals/sdcard-gpt-demo/Cargo.toml, examples/peripherals/sdcard-gpt-demo/src/main.rs
In previous development, we discovered that after updating the `embedded-sdmmc` version, the related examples could not run properly. At that time, we make a temporary fix by using an older version (https://github.com/rustsbi/bouffalo-hal/pull/6). 
Recently, I spent some time investigating the issue and found that it was due to the `embedded-sdmmc` using `SpiDevice` in the new version of the `embedded-hal`. Most operations on SPI were performed using the `Transfer` operation within the `transaction` function, which we had not implemented, leading to a panic.
In the older version of `embedded-hal`, the `SpiDevice` trait was not provided, and related operations were completed directly through functions like `transfer`. As a result, even if some functions were not implemented, they could …
=> spi: implement SpiBus and SpiDevice trait, update dependencies

Cargo.toml, bouffalo-hal/src/gpio.rs, examples/peripherals/sdh-demo/Cargo.toml, examples/peripherals/sdh-demo/README.md, examples/peripherals/sdh-demo/build.rs, examples/peripherals/sdh-demo/src/main.rs, examples/peripherals/sdh-demo/src/sdh.rs
Previously, we used the SPI interface to implement SD card read/write functionality. While this approach was effective, it required additional pin connections(see https://github.com/rustsbi/bouffalo-hal/blob/main/examples/peripherals/sdcard-demo/README.md) and had relatively slow data transfer speeds. To address these issues, we are now focusing on utilizing the SDH peripheral, which offers a more efficient and streamlined way to interact with SD cards.
We have developed a simple example that demonstrates the initialization of the SDH peripheral and reading data from an SD card. This example has been tested on the target hardware and is functioning correctly.
However, the current implementation is a basic demo intended for validation purposes. It relies on direct peripheral register …
=> sdh: add example for initializing and reading sdcard

bouffalo-hal/src/i2c.rs, examples/peripherals/i2c-demo/src/main.rs
=> i2c: add `max_retry` to i2c read and fix i2c-demo

examples/peripherals/uart-async-demo/Cargo.toml
Upgraded `panic-halt` and `riscv` dependencies to their latest versions.
=> build(deps): upgrade dependencies

bouffalo-hal/src/psram.rs
Recently, we found that some development boards had read and write errors in psram-demo. In this PR, we fixed this problem by comparing the values ​​of the registers with the official code.
Additionally, the psram initialization code is still mainly hard-coded. In the future, we will try to analyze it further for a deeper understanding.
Tested on my two M1s Dock development boards:
=> psram: fix read and write errors on some boards

bouffalo-rt/src/lib.rs, bouffalo-rt/src/soc/bl808.rs
This commit modified some fields According to the content of the image generated by the official BLDevcube, so that the generated image can be run directly. 
Previously, we compiled an image with:
`cargo build --target riscv64imac-unknown-none-elf --release -p sdcard-demo
rust-objcopy --binary-architecture=riscv64 --strip-all -O binary ./target/riscv64imac-unknown-none-elf/release/sdcard-demo ./target/riscv64imac-unknown-none-elf/release/sdcard-demo.bin`
And then flash in with the BLDEVCUBE GUI to run successfully.
Now that we've fixed the fields, run the following command on the compiled image to fix the checksum-related fields:
`cargo blri ./target/riscv64imac-unknown-none-elf/release/sdcard-demo.bin`
After that, we get a correct .bin file that can be run directly.
=> Fix the image header of bl808

blri/Cargo.toml, blri/src/main.rs
In this pull request, I've refactored the command-line interface of the blri tool and added a new `flash` command. This allows users to directly flash images to the development board via serial port, making the flashing process simpler and more convenient.
Taking `bouffalo-hal/bouffalo-rt/examples/blinky-bl808` as an example, from compilation to flashing, you only need to run the following commands:
```
cargo build -p blinky-bl808 --features bl808-dsp --target riscv64imac-unknown-none-elf --release
rust-objcopy --binary-architecture=riscv64 --strip-all -O binary ./target/riscv64imac-unknown-none-elf/release/blinky-bl808 ./target/riscv64imac-unknown-none-elf/release/blinky-bl808.bin
cargo blri patch ./target/riscv64imac-unknown-none-elf/release/blinky-bl808.bin
cargo blri flash …
```
=> feat(blri): add serial flashing support and refactor CLI structure

bouffalo-hal/src/uart/register.rs
The test results are shown below:
=> uart: add comprehensive test cases for UART RegisterBlock function

.github/workflows/Cargo.yml, Cargo.toml, bouffalo-hal/src/dma.rs, bouffalo-hal/src/glb/v2.rs, bouffalo-hal/src/uart/blocking.rs, bouffalo-rt/src/soc/bl808.rs, examples/peripherals/uart-async-demo/src/main.rs, examples/peripherals/uart-dma-demo/Cargo.toml, examples/peripherals/uart-dma-demo/README.md, examples/peripherals/uart-dma-demo/build.rs, examples/peripherals/uart-dma-demo/src/main.rs
This PR adds DMA support for UART, tested the TX functionality of DMA0 and UART0, which worked fine. Other usage has not been tested yet, but it can be achieved by modifying `DmaChannelConfig`, `LliPool`, and `LliPool`.
=> Add DMA support for UART peripheral and a new `uart-dma-demo` example

blri/src/lib.rs
This pull request fix the bug in calculate HAL_BOOTHEADER crc32 in blri. When the CRC value and the HASH value need to be updated at the same time, the unupdated hash value is used to calculate the crc, so the CRC value will be repaired error, and this PR solves this problem.
=> fix(blri): fix the bug in calculate HAL_BOOTHEADER crc32

blri/src/isp.rs, blri/src/lib.rs, blri/src/main.rs
This pull request includes:
- feat(blri): add reset feature for isp protocol
- fix(blri): code cleanup for main logic
- feat(blri): rearrange flash code using `UartIsp` structure
- feat(blri): add isp module, parse UART ISP protocol
=> feat(isp): code cleanup, add ISP module and UartIsp structure, implement ISP reset feature

.github/workflows/Cargo.yml, Cargo.toml, bouffalo-hal/src/dma.rs, bouffalo-hal/src/glb/v2.rs, bouffalo-hal/src/sdio.rs, bouffalo-rt/src/soc/bl616.rs, bouffalo-rt/src/soc/bl702.rs, bouffalo-rt/src/soc/bl808.rs, examples/README.md, examples/peripherals/sdh-dma-demo/Cargo.toml, examples/peripherals/sdh-dma-demo/README.md, examples/peripherals/sdh-dma-demo/build.rs, examples/peripherals/sdh-dma-demo/src/main.rs, examples/peripherals/uart-dma-demo/src/main.rs
- Add new example `sdh-dma-demo`.
- Use obtaining the register status to replace software delays for dma transmittion.
- Refacter `Dma` and `Sdh` structure.
- Split the workflow into two different architectures: riscv32 and riscv64.
=> feat(sdio): add dma support for sdh reading blocks and imporve code style

.cargo/config.toml, blri/src/main.rs
Such as, build PWM demo with: 
`cargo run --target riscv64imac-unknown-none-elf --release -p pwm-demo -- --port COM13`
Also, if we get the efl_file, the following command is equivalent to running the elf2bin patch and flash commands.
`cargo blri run ./target/riscv64imac-unknown-none-elf/release/pwm-demo -p COM13`
=> feat(blri): add run command in blri, use blri as project runner

bouffalo-hal/src/sdio/dma_sdh.rs
- `Ordering::SeqCst`: conforms to strict sequential consistency in memory access.
Refs: https://github.com/rustsbi/bouffalo-hal/pull/41#issuecomment-2799860760
Tested on m1s dock board with `sdh-dma-demo`, it works well.
=> fix(dma): update memory fence with `Ordering::SeqCst`

bouffalo-hal/src/gpio/flex_pad.rs, bouffalo-hal/src/gpio/mod.rs, bouffalo-hal/src/i2c/blocking.rs, bouffalo-hal/src/i2c/mod.rs, bouffalo-hal/src/i2c/pads.rs, bouffalo-hal/src/i2c/register.rs, bouffalo-hal/src/spi.rs, bouffalo-hal/src/spi/master.rs, bouffalo-hal/src/spi/mod.rs, bouffalo-hal/src/spi/pads.rs, bouffalo-rt/src/macros.rs, bouffalo-rt/src/soc/bl702/peripheral.rs, bouffalo-rt/src/soc/bl808/peripheral.rs, examples/peripherals/i2c-demo/src/main.rs, examples/peripherals/sdcard-demo/src/main.rs, examples/peripherals/sdcard-gpt-demo/src/main.rs, examples/peripherals/spi-demo/Cargo.toml, examples/peripherals/spi-demo/src/main.rs
Before:
```rust
let spi_clk = p.gpio.io3.into_spi::<1>();
let spi_mosi = p.gpio.io1.into_spi::<1>();
let spi_miso = p.gpio.io2.into_spi::<1>();
let spi_cs = p.gpio.io0.into_spi::<1>();
let spi_sd = Spi::new(
p.spi1,
(spi_clk, spi_mosi, spi_miso, spi_cs),
MODE_3,
&p.glb,
);
```
After:
```rust
let spi_clk = p.gpio.io3;
let spi_mosi = p.gpio.io1;
let spi_miso = p.gpio.io2;
let spi_cs = p.gpio.io0;
let pads = (spi_clk, spi_mosi, spi_miso, spi_cs);
let spi_sd = Spi::new(p.spi1, pads, MODE_3, &p.glb);
```
=> feat(hal): flexible pads, rearrange peripherals to use flexible pads

bouffalo-hal/src/gpio/flex_pad.rs, bouffalo-hal/src/lib.rs, bouffalo-hal/src/uart/asynch.rs, bouffalo-hal/src/uart/blocking.rs, bouffalo-hal/src/uart/config.rs, bouffalo-hal/src/uart/mod.rs, bouffalo-hal/src/uart/mux.rs, bouffalo-hal/src/uart/pad.rs, bouffalo-hal/src/uart/signal.rs, bouffalo-rt/src/macros.rs, bouffalo-rt/src/soc/bl808/peripheral.rs, examples/multicore/multicore-demo/dsp/src/main.rs, examples/peripherals/i2c-demo/src/main.rs, examples/peripherals/lz4d-demo/src/main.rs, examples/peripherals/psram-demo/src/main.rs, examples/peripherals/sdcard-demo/src/main.rs, examples/peripherals/sdcard-gpt-demo/src/main.rs, examples/peripherals/sdh-demo/src/main.rs, examples/peripherals/sdh-dma-demo/src/main.rs, examples/peripherals/uart-async-demo/src/main.rs, examples/peripherals/uart-cli-demo/src/main.rs, examples/peripherals/uart-demo/src/main.rs, examples/peripherals/uart-dma-demo/src/main.rs
This pull reqeust rearranges UART signal multiplexers and I/O pad constraints.
Before:
```rust
let tx = p.gpio.io14.into_uart();
let rx = p.gpio.io15.into_uart();
let sig2 = p.uart_muxes.sig2.into_transmit::<0>();
let sig3 = p.uart_muxes.sig3.into_receive::<0>();
let pads = ((tx, sig2), (rx, sig3));
let config = Config::default().set_baudrate(2000000.Bd());
let mut serial = p.uart0.freerun(config, pads, &c).unwrap();
```
After:
```rust
let tx = p.uart_muxes.sig2.into_transmit(p.gpio.io14);
let rx = p.uart_muxes.sig3.into_receive(p.gpio.io15);
let config = Config::default().set_baudrate(2000000.Bd());
let mut serial = p.uart0.freerun(config, (tx, rx), &c).unwrap();
```
=> refactor(hal): simplify UART peripheral implementation using flexible pads
